name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-alpinex-86:
    name: Alpine ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x86]

    steps:
    - uses: actions/checkout@v3

    - name: Install latest stable Alpine Linux
      uses: jirutka/setup-alpine@master
      with:
        arch: ${{ matrix.Platform }}
        branch: 'latest-stable'
        packages: build-base cmake bison flex nasm xz sed sdl2-dev zlib-dev libogg-dev libvorbis-dev
        
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"
        
    - name: Run CMake
      shell: alpine.sh {0}
      run: |
        cd ${{github.workspace}}/Sources 
        find . -name "CMakeLists.txt" -exec sed -i 's/-march=native/-mtune=generic/g' {} +
        cat CMakeLists.txt | grep mtune
        CFLAGS="-w" CXXFLAGS="-w" cmake -B ${{github.workspace}}/Sources/build-x86 -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DCMAKE_C_FLAGS=-mmmx -DCMAKE_CXX_FLAGS=-mmmx -DUSE_I386_NASM_ASM=TRUE -DTFE=TRUE
        CFLAGS="-w" CXXFLAGS="-w" cmake -B ${{github.workspace}}/Sources/build-x86-xplus -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DCMAKE_C_FLAGS=-mmmx -DCMAKE_CXX_FLAGS=-mmmx -DUSE_I386_NASM_ASM=TRUE -DTFE=TRUE

    - name: Run Build
      shell: alpine.sh {0}
      run: |
          cd ${{github.workspace}}/Sources/build-x86    
          make ecc
          make -j$(nproc || echo 4)
          cp -vfr Debug/*.so ../../x32/SamTFE/Mods/JumpFUN/Bin
          cp -vfr ../../Sources/Entities/PlayerWeaponsHD.es ../../Sources/Entities/PlayerWeapons.es
          cd ${{github.workspace}}/Sources/build-x86-xplus    
          make ecc
          make -j$(nproc || echo 4)
          cp -vfr Debug/*.so ../../x32/SamTFE/Mods/JumpFUNHD/Bin
          cd ${{github.workspace}}
          tar -cJpvf SamTFE-JumpFUN-${{ steps.date.outputs.time }}-alpine-x86-bin.tar.xz x32
          
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-alpine-x86-bin.tar.xz
        path: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-alpine-x86-bin.tar.xz          

  build-alpinex-64:
    name: Alpine ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x86_64]

    steps:
    - uses: actions/checkout@v3

    - name: Install latest stable Alpine Linux
      uses: jirutka/setup-alpine@master
      with:
        arch: ${{ matrix.Platform }}
        branch: 'latest-stable'
        packages: build-base cmake bison flex nasm xz sed sdl2-dev zlib-dev libogg-dev libvorbis-dev
        
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"
        
    - name: Run CMake
      shell: alpine.sh {0}
      run: |
        cd ${{github.workspace}}/Sources 
        find . -name "CMakeLists.txt" -exec sed -i 's/-march=native/-mtune=generic/g' {} +
        cat CMakeLists.txt | grep mtune
        CFLAGS="-w" CXXFLAGS="-w" cmake -B ${{github.workspace}}/Sources/build-x64 -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DTFE=TRUE
        CFLAGS="-w" CXXFLAGS="-w" cmake -B ${{github.workspace}}/Sources/build-x64-xplus -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DTFE=TRUE

    - name: Run Build
      shell: alpine.sh {0}
      run: |
          cd ${{github.workspace}}/Sources/build-x64    
          make ecc
          make -j$(nproc || echo 4)
          cp -vfr Debug/*.so ../../x64/SamTFE/Mods/JumpFUN/Bin
          cp -vfr ../../Sources/Entities/PlayerWeaponsHD.es ../../Sources/Entities/PlayerWeapons.es
          cd ${{github.workspace}}/Sources/build-x64-xplus    
          make ecc
          make -j$(nproc || echo 4)
          cp -vfr Debug/*.so ../../x64/SamTFE/Mods/JumpFUNHD/Bin
          cd ${{github.workspace}}
          tar -cJpvf SamTFE-JumpFUN-${{ steps.date.outputs.time }}-alpine-x86_64-bin.tar.xz x64
          
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-alpine-x86_64-bin.tar.xz
        path: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-alpine-x86_64-bin.tar.xz          


  build-ubuntu-x64:
    name: Ubuntu ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y libsdl2-dev libogg-dev libvorbis-dev &&
          sudo apt-get install -qq -y bison flex sed zlib1g-dev      

    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"
        
    - name: Run CMake
      run: |
          cd ${{github.workspace}}/Sources
          find . -name "CMakeLists.txt" -exec sed -i 's/-march=native/-mtune=generic/g' {} +
          cat CMakeLists.txt | grep mtune
          cmake -B ${{github.workspace}}/Sources/build-x64 -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DTFE=TRUE
          
    - name: Run Build
      run: |
          cd ${{github.workspace}}/Sources/build-x64    
          make ecc
          make -j$(nproc || echo 4)
          cp -vfr Debug/*.so ../../x64/SamTFE/Mods/JumpFUN/Bin
          
    - name: Run CMake
      run: |
          cd ${{github.workspace}}/Sources
          cp -vfr Entities/PlayerWeaponsHD.es Entities/PlayerWeapons.es
          cat CMakeLists.txt | grep mtune
          cmake -B ${{github.workspace}}/Sources/build-x64-xplus -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DTFE=TRUE
          
    - name: Run Build
      run: |
          cd ${{github.workspace}}/Sources/build-x64-xplus    
          make ecc
          make -j$(nproc || echo 4)
          cp -vfr Debug/*.so ../../x64/SamTFE/Mods/JumpFUNHD/Bin          
          cd ${{github.workspace}}
          XZ_DEFAULTS="-T 10" tar --use-compress-program=xz -cpvf SamTFE-JumpFUN-${{ steps.date.outputs.time }}-lnx-amd64-bin.tar.xz x64
          
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-lnx-amd64-bin.tar.xz
        path: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-lnx-amd64-bin.tar.xz 

  build-windows-x86:
    name: Windows ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [Win32]
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: '14.0'
        
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"
 
    - name: MS Build
      working-directory: Sources
      run: |
         del Entities\PlayerWeapons.es
         copy Entities\PlayerWeaponsHD.es Entities\PlayerWeapons.es
         msbuild /m /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" JumpFUN.sln
         cd ${{github.workspace}}
         copy x32\SamTFE\Mods\JumpFUN\Bin\*.dll x32\SamTFE\Mods\JumpFUNHD\Bin    
         del x32\SamTFE\Mods\JumpFUN\Bin\*.*
         
    - name: MS Build
      working-directory: Sources
      run: |         
         del Entities\PlayerWeapons.es
         copy Entities\PlayerWeapons_old.es Entities\PlayerWeapons.es 
         msbuild /t:Clean /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" JumpFUN.sln
         msbuild /m /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" JumpFUN.sln       
         cd ${{github.workspace}}        
         del x32\SamTFE\Mods\JumpFUN\Bin\*.lib 
         del x32\SamTFE\Mods\JumpFUN\Bin\*.exe 
         del x32\SamTFE\Mods\JumpFUN\Bin\*.map        
         7z a -mx=9 SamTFE-JumpFUN-${{ steps.date.outputs.time }}-win32-bin.7z x32
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-win32-bin.7z
        path: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-win32-bin.7z 
        
  build-windows-x64:
    name: Windows ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]
    steps:
    - uses: actions/checkout@v3

    - uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: '14.0'

    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"
        
    - name: MS Build
      working-directory: Sources
      run: |
         del Entities\PlayerWeapons.es
         copy Entities\PlayerWeaponsHD.es Entities\PlayerWeapons.es
         msbuild /m /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" JumpFUN.sln
         cd ${{github.workspace}}
         copy x64\SamTFE\Mods\JumpFUN\Bin\*.dll x64\SamTFE\Mods\JumpFUNHD\Bin    
         del x64\SamTFE\Mods\JumpFUN\Bin\*.*
         
    - name: MS Build
      working-directory: Sources
      run: |         
         del Entities\PlayerWeapons.es
         copy Entities\PlayerWeapons_old.es Entities\PlayerWeapons.es 
         msbuild /t:Clean /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" JumpFUN.sln
         msbuild /m /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" JumpFUN.sln       
         cd ${{github.workspace}}        
         del x64\SamTFE\Mods\JumpFUN\Bin\*.lib 
         del x64\SamTFE\Mods\JumpFUN\Bin\*.exe 
         del x64\SamTFE\Mods\JumpFUN\Bin\*.map        
         7z a -mx=9 SamTFE-JumpFUN-${{ steps.date.outputs.time }}-win64-bin.7z x64
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-win64-bin.7z
        path: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-win64-bin.7z        

  build-freebsd-x64:
    name: FreeBSD ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]    
    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYYMMDD"

      - name: Show current date
        run: |
          echo "${{ steps.date.outputs.time }}"
          
      - name: Build on FreeBSD
        uses: cross-platform-actions/action@v0.10.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.1'
          shell: bash
          run: |
            uname -a
            sudo pkg install -y bison flex sdl2 libogg libvorbis zlib-ng cmake
            cd ${{github.workspace}}/Sources
            awk '{sub("-march=native","-mtune=generic")}1' CMakeLists.txt > CmakeTemp.txt && mv CmakeTemp.txt CMakeLists.txt
            cat CMakeLists.txt | grep mtune
            cmake -B ${{github.workspace}}/Sources/build-x64 -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DTFE=TRUE
            cmake -B ${{github.workspace}}/Sources/build-x64-xplus -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DTFE=TRUE
            cd ${{github.workspace}}/Sources/build-x64
            make ecc
            make -j$(sysctl -n hw.ncpu || echo 4)
            cp -vfr Debug/*.so ../../x64/SamTFE/Mods/JumpFUN/Bin
            cp -vfr ../../Sources/Entities/PlayerWeaponsHD.es ../../Sources/Entities/PlayerWeapons.es
            cd ${{github.workspace}}/Sources/build-x64-xplus
            make ecc
            make -j$(sysctl -n hw.ncpu || echo 4)
            cp -vfr Debug/*.so ../../x64/SamTFE/Mods/JumpFUNHD/Bin
            cd ${{github.workspace}}
            XZ_DEFAULTS="-T 10" tar --use-compress-program=xz -cpvf SamTFE-JumpFUN-${{ steps.date.outputs.time }}-bsd-amd64-bin.tar.xz x64
                      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-bsd-amd64-bin.tar.xz
          path: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-bsd-amd64-bin.tar.xz      
    
  build-raspios-armv7l:
    name: RPi OS Lite ${{ matrix.Configuration }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7l]
        Configuration: [Release]      
        include:
        - arch: armv7l
          cpu: cortex-a53
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_3b
         
    steps:
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"    
    
    - uses: pguyot/arm-runner-action@v2
      with:
        image_additional_mb: 1024
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        shell: /bin/bash 
        copy_artifact_path: Release
        commands: |
            mkdir Release
            test `uname -m` = ${{ matrix.arch }}
            grep Model /proc/cpuinfo
            apt-get update -y --allow-releaseinfo-change
            apt-get install --no-install-recommends -y git bison flex cmake make gcc libc6-dev libsdl2-dev libogg-dev libvorbis-dev zlib1g-dev    
            cat /proc/cpuinfo
            cat /etc/os-release
            uname -a
            gcc -c -Q -mcpu=native --help=target
            git clone https://github.com/tx00100xt/SE1-TFE-JumpFUN.git
            cmake SE1-TFE-JumpFUN/Sources -B SE1-TFE-JumpFUN/Sources/build-armv7l -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DUSE_I386_NASM_ASM=FALSE -DTFE=TRUE -DRPI4=TRIE
            cmake SE1-TFE-JumpFUN/Sources -B SE1-TFE-JumpFUN/Sources/build-armv7l-xplus -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DUSE_I386_NASM_ASM=FALSE -DTFE=TRUE -DRPI4=TRIE
            make -C SE1-TFE-JumpFUN/Sources/build-armv7l ecc
            make -j4 -C SE1-TFE-JumpFUN/Sources/build-armv7l
            cp -vfr SE1-TFE-JumpFUN/Sources/build-armv7l/Debug/*.so SE1-TFE-JumpFUN/x32/SamTFE/Mods/JumpFUN/Bin 
            cp -vfr SE1-TFE-JumpFUN/Sources/Entities/PlayerWeaponsHD.es SE1-TFE-JumpFUN/Sources/Entities/PlayerWeapons.es
            make -C SE1-TFE-JumpFUN/Sources/build-armv7l-xplus ecc
            make -j4 -C SE1-TFE-JumpFUN/Sources/build-armv7l-xplus
            cp -vfr SE1-TFE-JumpFUN/Sources/build-armv7l-xplus/Debug/*.so SE1-TFE-JumpFUN/x32/SamTFE/Mods/JumpFUNHD/Bin            
            mv SE1-TFE-JumpFUN/x32 armv7l
            XZ_DEFAULTS="-T 10" tar --use-compress-program=xz -cpvf SamTFE-JumpFUN-${{ steps.date.outputs.time }}-rpios-armv7l-bin.tar.xz armv7l
            cp SamTFE-JumpFUN-${{ steps.date.outputs.time }}-rpios-armv7l-bin.tar.xz Release/
    - name: Prepare Release
      run: |           
         sudo mv ${{github.workspace}}/Release/SamTFE-JumpFUN-${{ steps.date.outputs.time }}-rpios-armv7l-bin.tar.xz ${{github.workspace}}/
                        
    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-rpios-armv7l-bin.tar.xz
        path: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-rpios-armv7l-bin.tar.xz
        
  build-raspios-aarch64:
    name: RPi OS Lite ${{ matrix.Configuration }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64]
        Configuration: [Release]      
        include:
        - arch: aarch64
          cpu: cortex-a72
          base_image: raspios_lite_arm64:latest
          cpu_info: cpuinfo/raspberrypi_4b
         
    steps:
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"    
    
    - uses: pguyot/arm-runner-action@v2
      with:
        image_additional_mb: 1024
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        shell: /bin/bash 
        copy_artifact_path: Release
        commands: |
            mkdir Release
            test `uname -m` = ${{ matrix.arch }}
            grep Model /proc/cpuinfo
            apt-get update -y --allow-releaseinfo-change
            apt-get install --no-install-recommends -y git bison flex cmake make gcc libc6-dev libsdl2-dev libogg-dev libvorbis-dev zlib1g-dev    
            cat /proc/cpuinfo
            cat /etc/os-release
            uname -a
            gcc -c -Q -mcpu=native --help=target
            git clone https://github.com/tx00100xt/SE1-TFE-JumpFUN.git
            cmake SE1-TFE-JumpFUN/Sources -B SE1-TFE-JumpFUN/Sources/build-aarch64 -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DTFE=TRUE -DRPI4=TRIE
            cmake SE1-TFE-JumpFUN/Sources -B SE1-TFE-JumpFUN/Sources/build-aarch64-xplus -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DTFE=TRUE -DRPI4=TRIE
            make -C SE1-TFE-JumpFUN/Sources/build-aarch64 ecc
            make -j4 -C SE1-TFE-JumpFUN/Sources/build-aarch64
            cp -vfr SE1-TFE-JumpFUN/Sources/build-aarch64/Debug/*.so SE1-TFE-JumpFUN/x64/SamTFE/Mods/JumpFUN/Bin 
            cp -vfr SE1-TFE-JumpFUN/Sources/Entities/PlayerWeaponsHD.es SE1-TFE-JumpFUN/Sources/Entities/PlayerWeapons.es
            make -C SE1-TFE-JumpFUN/Sources/build-aarch64-xplus ecc
            make -j4 -C SE1-TFE-JumpFUN/Sources/build-aarch64-xplus
            cp -vfr SE1-TFE-JumpFUN/Sources/build-aarch64-xplus/Debug/*.so SE1-TFE-JumpFUN/x64/SamTFE/Mods/JumpFUNHD/Bin           
            mv SE1-TFE-JumpFUN/x64 aarch64
            XZ_DEFAULTS="-T 10" tar --use-compress-program=xz -cpvf SamTFE-JumpFUN-${{ steps.date.outputs.time }}-rpios-aarch64-bin.tar.xz aarch64
            cp SamTFE-JumpFUN-${{ steps.date.outputs.time }}-rpios-aarch64-bin.tar.xz Release/
    - name: Prepare Release
      run: |           
         sudo mv ${{github.workspace}}/Release/SamTFE-JumpFUN-${{ steps.date.outputs.time }}-rpios-aarch64-bin.tar.xz ${{github.workspace}}/
                        
    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-rpios-aarch64-bin.tar.xz
        path: SamTFE-JumpFUN-${{ steps.date.outputs.time }}-rpios-aarch64-bin.tar.xz
